name: Run Proxies

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20' 

    - name: Create proxies directory
      run: mkdir -p proxies

    - name: Run http.go
      run: go run http.go

    - name: Move http proxies to proxies directory
      run: mv http.txt ./proxies/http.txt

    - name: Run socks.go
      run: go run socks.go
    
    - name: Move socks proxies to proxies directory
      run: mv socks.txt ./proxies/socks.txt

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions Bot"

    - name: Commit and push changes
      run: |
        git add proxies/http.txt proxies/socks.txt
        git commit -m "update proxies" || echo "Nothing to commit"
        git push
